### PR TITLE
A readme, some docs, and a small bugfix

### PR DESCRIPTION
**Pull request by iislucas**
This change is [Reviewable](https://reviewable.io/reviews/ewulczyn/wiki-detox/3)

### CODE REVIEW

**Comment by nithum** [comment]
Hi @iislucas, is this ready for merger? 

It looks like the sentence in the README.md, there is a partial sentence under "Setup datasets and train models from Figshare data".

**Comment by nithum** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 41 at r1](https://reviewable.io:443/reviews/ewulczyn/wiki-detox/3#-KgASvchvrsumwTYR3fO:-KgASvci36AUtN6WtEjP:bmj14tc) ([raw file](https://github.com/ewulczyn/wiki-detox/blob/b8274f41e771448a38d8b0161ebd7913c2460ef8/README.md#L41)):*
> ```Markdown
> # Setup datasets and train models from Figshare data
> 
> Assuming you've
> ```

Incomplete sentence

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ewulczyn/wiki-detox/3)*

**Comment by nithum** [comment]
Reviewed 4 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ewulczyn/wiki-detox/3)*

**Comment by iislucas** [comment]
Completed the sentence. :)

**Comment by iislucas** [comment]
This is a step in the direction I'd like to go of making this work more easily re-usable; there's a lot of stuff about the dependencies of notebooks that is not very clear at the moment and we should clarify. Probably by setting up some toy-data for a test-case, and having an integration test that checks all the code runs.

**Comment by nithum** [comment]
Agreed. I can try to set this up when I'm back from WWW. @ewulczyn, do you have some time before then?

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ewulczyn/wiki-detox/3#-:-KgGZriPiQDY_eQWMAEB:by1df8z)*

**Comment by nithum** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ewulczyn/wiki-detox/3#-:-KgG_GRz_gGNejYmKBxN:bnfp4nl)*

**Pull request merged**
